# Generated by Django 2.1.7 on 2019-03-03 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_date', models.DateField()),
                ('drop_date', models.DateField()),
                ('dest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.DrugStock')),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='service.Supply')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
